parameters:
  syzygy.mail.composer.class: Syzygy\FrameworkBundle\Mail\Composer
  mail_from: ""
  mail_subject: ""
  mail_global_vars: []

services:
  syzygy.mail.composer:
    class: %syzygy.mail.composer.class%
    arguments: [@mailer, @twig]
    calls:
      - [setDefaultFrom, [%mail_from%]]
      - [setDefaultSubject, [%mail_subject%]]
      - [setGlobalVars, [%mail_global_vars%]]
